sudo: required
dist: bionic
language: csharp
mono: none
dotnet: 3.1
services: docker
before_install:
  - cd RestWithASPNET5
  - echo "We are in the right folder!"
script:
  - docker-compose build
before_deploy:
  - echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin
deploy:
  provider: script
  script:
    docker tag Rest-with-asp-net-mesaradionica:latest $DOCKER_USERNAME/rest-with-asp-net-udemy:$TRAVIS_JOB_ID;
    docker push $DOCKER_USERNAME/rest-with-asp-net-udemy:$TRAVIS_JOB_ID;    
  on:
    branch: master
notifications:
  email: false


r 